modLoader="javafml"
loaderVersion="${loader_version_range}"
license="Apache-2.0 License"

[[mods]]
modId="massmunitions"
version="1.20.1-1.0.0"
displayName="Create: Mass Munitions"
displayURL="test1 / test2"
logoFile="cmm_logo.png"
credits="MarbledNull, MelodicCougar7, Corrine"
authors="MarbledNull, MelodicCougar7"

description='''A mod that adds mass production compatibility between Create and TaCZ/VPB'''
[[dependencies.massmunitions]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.massmunitions]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.massmunitions]]
    modId="create"
    mandatory=true
    versionRange="0.5.1.h,"
    ordering="NONE"
    side="BOTH"
[[dependencies.massmunitions]]
    modId="pointblank"
    mandatory=false
    versionRange="1.7.6,"
    ordering="NONE"
    side="BOTH"
[[dependencies.massmunitions]]
    modId="tacz"
    mandatory=false
    versionRange="1.0.3,"
    ordering="NONE"
    side="BOTH"
